// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ndznjiqqgswtnultlxkz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5kem5qaXFxZ3N3dG51bHRseGt6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzQwMjk0NjcsImV4cCI6MjA0OTYwNTQ2N30.IFUN9ALBpQD46kqmKdj1gC8v3yztHhv-bV3SjuLofH4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);